# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  nats:
    image: nats:2
    command: ["-js"]
    ports: ["4222:4222","8222:8222"]

  user-svc:
    build: ./services/user
    environment:
      DATABASE_URL: postgres://app:password@postgres:5432/appdb?sslmode=disable
      JWT_SECRET: "supersecret"
    depends_on: [postgres]
    ports: ["8081:8080"]

  trip-svc:
    build: ./services/trip
    environment:
      DATABASE_URL: postgres://app:password@postgres:5432/appdb?sslmode=disable
      NATS_URL: nats://nats:4222
      JWT_PUBLIC_KEY_PEM: |
        -----BEGIN PUBLIC KEY-----
        # paste from UserService keypair if using RS256
        -----END PUBLIC KEY-----
    depends_on: [postgres, nats]
    ports: ["8082:8080"]

  driver-svc:
    build: ./services/driver
    environment:
      REDIS_ADDR: redis:6379
      NATS_URL: nats://nats:4222
    depends_on: [redis, nats]
    ports: ["8083:8080"]

volumes:
  pgdata:
