# ==============================
# NATS configuration file
# ==============================

server_name: "n1"

# Ports
port: 4222

# JetStream storage (for durable subjects)
jetstream {
  store_dir: "/var/lib/nats/jetstream"
  max_mem_store: 1Gb
  max_file_store: 10Gb
}

# Optional monitoring HTTP endpoint
http: {
  host: "0.0.0.0"
  port: 8222
}

# Enable this cluster section later if you want to run 3 nodes
# cluster {
#   name: "uitgo-nats"
#   listen: "0.0.0.0:6222"
#   routes: [
#     nats-route://n2:6222,
#     nats-route://n3:6222
#   ]
# }

# Logging
debug: false
trace: false
logtime: true
